version: '2.1'

services:

  elasticsearch:
    image: tonyhernandezatms/elasticsearch:openjdk8-nanoserver-sac2016-ES_5.5.3
    build: ./ElasticSearch/nanoserver
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - '.\ElasticSearch\nanoserver\data:C:\data'
    stdin_open: true
    tty: true

  kibana:
    image: tonyhernandezatms/kibana:windowsservercore-ltsc2016-ES_5.5.3
    build: ./Kibana/windowsservercore
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: ${hostname}
      ELASTICSEARCH_URL: http://elasticsearch:9200

networks:
  default:
    external:
      name: nat