version: '2.1'

services:

  elasticsearch:
    image: tonyhernandezatms/elasticsearch:openjdk8-nanoserver-sac2016-ES_5.5.3
    build: ./ElasticSearch/nanoserver
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - '.\ElasticSearch\nanoserver\data:C:\data'
      - '.\ElasticSearch\nanoserver\config:C:\config'
      - '.\ElasticSearch\nanoserver\logs:C:\logs'
    stdin_open: true
    tty: true
    environment:


  kibana:
    image: tonyhernandezatms/kibana:windowsservercore-ltsc2016-ES_5.5.3
    build: ./Kibana/windowsservercore
    hostname: kibana
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: localkibana
      ELASTICSEARCH_URL: http://localES
      
networks:
  default:
    external:
      name: nat